2024-01-24 13:16:07.807 [info] Experiment 'pythonRecommendTensorboardExtcf' is active
2024-01-24 13:16:07.807 [info] Experiment 'pythonREPLSmartSend' is active
2024-01-24 13:16:07.807 [info] Experiment 'pythonSurveyNotification' is active
2024-01-24 13:16:07.807 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2024-01-24 13:16:07.807 [info] Experiment 'pythonTestAdapter' is active
2024-01-24 13:16:07.863 [info] Default formatter is set to null for workspace /home/diego/Downloads/Classificazione_Malattie_Cardiovascolari
2024-01-24 13:16:07.887 [info] Test server listening.
2024-01-24 13:16:07.894 [info] > conda info --json
2024-01-24 13:16:08.247 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-01-24 13:16:08.247 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-01-24 13:16:08.247 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-01-24 13:16:08.247 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-01-24 13:16:08.247 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-01-24 13:16:08.247 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-01-24 13:16:08.248 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2024-01-24 13:16:08.248 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2024-01-24 13:16:08.248 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2024-01-24 13:16:08.248 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2024-01-24 13:16:08.248 [info] Found: /bin/python --> /bin/python3.11
2024-01-24 13:16:08.260 [info] Found: /bin/python3 --> /bin/python3.11
2024-01-24 13:16:08.261 [info] Found: /bin/python3.11 --> /bin/python3.11
2024-01-24 13:16:08.290 [info] Found: /sbin/python --> /sbin/python3.11
2024-01-24 13:16:08.290 [info] Found: /sbin/python3 --> /sbin/python3.11
2024-01-24 13:16:08.291 [info] Found: /sbin/python3.11 --> /sbin/python3.11
2024-01-24 13:16:08.307 [info] Found: /usr/bin/python --> /usr/bin/python3.11
2024-01-24 13:16:08.307 [info] Found: /usr/bin/python3 --> /usr/bin/python3.11
2024-01-24 13:16:08.308 [info] Found: /usr/bin/python3.11 --> /usr/bin/python3.11
2024-01-24 13:16:08.323 [info] Found: /usr/sbin/python --> /usr/sbin/python3.11
2024-01-24 13:16:08.323 [info] Found: /usr/sbin/python3 --> /usr/sbin/python3.11
2024-01-24 13:16:08.323 [info] Found: /usr/sbin/python3.11 --> /usr/sbin/python3.11
2024-01-24 13:16:08.339 [info] > /bin/python -I ~/.vscode/extensions/ms-python.python-2023.22.1/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.22.1/pythonFiles/interpreterInfo.py
2024-01-24 13:16:08.359 [info] > /sbin/python -I ~/.vscode/extensions/ms-python.python-2023.22.1/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.22.1/pythonFiles/interpreterInfo.py
2024-01-24 13:16:08.413 [info] > /usr/bin/python -I ~/.vscode/extensions/ms-python.python-2023.22.1/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.22.1/pythonFiles/interpreterInfo.py
2024-01-24 13:16:08.424 [info] > /usr/sbin/python -I ~/.vscode/extensions/ms-python.python-2023.22.1/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.22.1/pythonFiles/interpreterInfo.py
2024-01-24 13:16:08.505 [info] Python interpreter path: /bin/python
2024-01-24 13:16:08.513 [info] Send text to terminal: echo /usr/bin/zsh
2024-01-24 13:16:08.545 [warning] Retry failed, storage update failed for key PYTHON_GLOBAL_STORAGE_KEYS
2024-01-24 13:16:10.220 [info] Starting Pylance language server.
2024-01-24 13:16:11.558 [info] Shell integration is not working for zsh
2024-01-24 13:16:11.559 [warning] Shell integration is not active, environment activated maybe overriden by the shell.
